version: '3.5'
services:
  search_api:
    container_name: 'search_api'
    build: ./search-api
    restart: 'on-failure'
    ports:
      - '8080:8080'
#    depends_on: ['elasticsearch']

#  elasticsearch:
#    container_name: 'elasticsearch'
#    image: elasticsearch:6.5.0
#    command: elasticsearch -E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1
#    ports:
#      - '9200:9200'
#      - '9300:9300'
#    volumes:
#      - es_data:/usr/share/elasticsearch/data

  logstash:
    container_name: 'logstash'
    image: logstash:6.5.0
    command: bash -c "logstash -f /tmp/logstash.conf"
    volumes:
      - ./logstash.conf:/tmp/logstash.conf
      - /home/ftpusers/ampowerMPO/ampowerMPO:/tmp/data
#    depends_on: ['elasticsearch']

#  kibana:
#    container_name: 'kibana'
#    image: kibana:5
#    ports:
#      - '5601:5601'
#    depends_on: ['elasticsearch']

#volumes:
#  es_data:
